# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.calibrationFileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.calibrationFileLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationFileLineEdit.sizePolicy().hasHeightForWidth())
        self.calibrationFileLineEdit.setSizePolicy(sizePolicy)
        self.calibrationFileLineEdit.setObjectName("calibrationFileLineEdit")
        self.horizontalLayout_10.addWidget(self.calibrationFileLineEdit)
        self.calibrationFileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrationFileBrowseButton.setEnabled(True)
        self.calibrationFileBrowseButton.setObjectName("calibrationFileBrowseButton")
        self.horizontalLayout_10.addWidget(self.calibrationFileBrowseButton)
        self.horizontalLayout_10.setStretch(0, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.firstKineticFileListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstKineticFileListWidget.sizePolicy().hasHeightForWidth())
        self.firstKineticFileListWidget.setSizePolicy(sizePolicy)
        self.firstKineticFileListWidget.setObjectName("firstKineticFileListWidget")
        self.verticalLayout_11.addWidget(self.firstKineticFileListWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_15.addItem(spacerItem)
        self.firstKineticBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.firstKineticBrowseButton.setObjectName("firstKineticBrowseButton")
        self.verticalLayout_15.addWidget(self.firstKineticBrowseButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.firstKineticStartTimeListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstKineticStartTimeListWidget.sizePolicy().hasHeightForWidth())
        self.firstKineticStartTimeListWidget.setSizePolicy(sizePolicy)
        self.firstKineticStartTimeListWidget.setObjectName("firstKineticStartTimeListWidget")
        self.verticalLayout_14.addWidget(self.firstKineticStartTimeListWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.firstKineticGateStepListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstKineticGateStepListWidget.sizePolicy().hasHeightForWidth())
        self.firstKineticGateStepListWidget.setSizePolicy(sizePolicy)
        self.firstKineticGateStepListWidget.setObjectName("firstKineticGateStepListWidget")
        self.verticalLayout_13.addWidget(self.firstKineticGateStepListWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.firstBackgroundLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.firstBackgroundLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstBackgroundLineEdit.sizePolicy().hasHeightForWidth())
        self.firstBackgroundLineEdit.setSizePolicy(sizePolicy)
        self.firstBackgroundLineEdit.setObjectName("firstBackgroundLineEdit")
        self.verticalLayout_12.addWidget(self.firstBackgroundLineEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 1)
        self.horizontalLayout_9.setStretch(4, 3)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.kineticsFilesListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kineticsFilesListWidget.sizePolicy().hasHeightForWidth())
        self.kineticsFilesListWidget.setSizePolicy(sizePolicy)
        self.kineticsFilesListWidget.setAcceptDrops(True)
        self.kineticsFilesListWidget.setDragEnabled(True)
        self.kineticsFilesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.kineticsFilesListWidget.setMovement(QtWidgets.QListView.Snap)
        self.kineticsFilesListWidget.setObjectName("kineticsFilesListWidget")
        self.horizontalLayout_8.addWidget(self.kineticsFilesListWidget)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.kineticFilesBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.kineticFilesBrowseButton.setObjectName("kineticFilesBrowseButton")
        self.verticalLayout_10.addWidget(self.kineticFilesBrowseButton)
        self.moveUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveUpButton.setObjectName("moveUpButton")
        self.verticalLayout_10.addWidget(self.moveUpButton)
        self.moveDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveDownButton.setObjectName("moveDownButton")
        self.verticalLayout_10.addWidget(self.moveDownButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_10.addWidget(self.deleteButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.startTimesListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimesListWidget.sizePolicy().hasHeightForWidth())
        self.startTimesListWidget.setSizePolicy(sizePolicy)
        self.startTimesListWidget.setObjectName("startTimesListWidget")
        self.horizontalLayout_8.addWidget(self.startTimesListWidget)
        self.gateStepListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gateStepListWidget.sizePolicy().hasHeightForWidth())
        self.gateStepListWidget.setSizePolicy(sizePolicy)
        self.gateStepListWidget.setObjectName("gateStepListWidget")
        self.horizontalLayout_8.addWidget(self.gateStepListWidget)
        self.backgroundFilesListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundFilesListWidget.sizePolicy().hasHeightForWidth())
        self.backgroundFilesListWidget.setSizePolicy(sizePolicy)
        self.backgroundFilesListWidget.setAcceptDrops(True)
        self.backgroundFilesListWidget.setDragEnabled(True)
        self.backgroundFilesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.backgroundFilesListWidget.setMovement(QtWidgets.QListView.Snap)
        self.backgroundFilesListWidget.setObjectName("backgroundFilesListWidget")
        self.horizontalLayout_8.addWidget(self.backgroundFilesListWidget)
        self.horizontalLayout_8.setStretch(0, 3)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 1)
        self.horizontalLayout_8.setStretch(4, 3)
        self.verticalLayout_17.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.timeSlicesGbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSlicesGbox.sizePolicy().hasHeightForWidth())
        self.timeSlicesGbox.setSizePolicy(sizePolicy)
        self.timeSlicesGbox.setObjectName("timeSlicesGbox")
        self.layoutWidget = QtWidgets.QWidget(self.timeSlicesGbox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 511, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.timeSliceDisplay = MplWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSliceDisplay.sizePolicy().hasHeightForWidth())
        self.timeSliceDisplay.setSizePolicy(sizePolicy)
        self.timeSliceDisplay.setObjectName("timeSliceDisplay")
        self.verticalLayout_9.addWidget(self.timeSliceDisplay)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.timeSliceWlMinSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.timeSliceWlMinSpinBox.setEnabled(False)
        self.timeSliceWlMinSpinBox.setMaximum(2000.0)
        self.timeSliceWlMinSpinBox.setObjectName("timeSliceWlMinSpinBox")
        self.horizontalLayout_6.addWidget(self.timeSliceWlMinSpinBox)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.timeSliceWlMaxSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.timeSliceWlMaxSpinBox.setEnabled(False)
        self.timeSliceWlMaxSpinBox.setMaximum(2000.0)
        self.timeSliceWlMaxSpinBox.setProperty("value", 2000.0)
        self.timeSliceWlMaxSpinBox.setObjectName("timeSliceWlMaxSpinBox")
        self.horizontalLayout_6.addWidget(self.timeSliceWlMaxSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.timeSlider = QtWidgets.QScrollBar(self.layoutWidget)
        self.timeSlider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeSlider.sizePolicy().hasHeightForWidth())
        self.timeSlider.setSizePolicy(sizePolicy)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_7.addWidget(self.timeSlider)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.autoscaleCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.autoscaleCheckBox.setEnabled(False)
        self.autoscaleCheckBox.setChecked(True)
        self.autoscaleCheckBox.setObjectName("autoscaleCheckBox")
        self.verticalLayout_8.addWidget(self.autoscaleCheckBox)
        self.scaleButton = QtWidgets.QPushButton(self.layoutWidget)
        self.scaleButton.setEnabled(False)
        self.scaleButton.setObjectName("scaleButton")
        self.verticalLayout_8.addWidget(self.scaleButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.setStretch(0, 1)
        self.horizontalLayout_11.addWidget(self.timeSlicesGbox)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.dataCorrectionGbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataCorrectionGbox.sizePolicy().hasHeightForWidth())
        self.dataCorrectionGbox.setSizePolicy(sizePolicy)
        self.dataCorrectionGbox.setObjectName("dataCorrectionGbox")
        self.layoutWidget1 = QtWidgets.QWidget(self.dataCorrectionGbox)
        self.layoutWidget1.setGeometry(QtCore.QRect(8, 20, 521, 76))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.delimiterComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.delimiterComboBox.setObjectName("delimiterComboBox")
        self.verticalLayout_5.addWidget(self.delimiterComboBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.loadButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_4.addWidget(self.loadButton)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.timeZeroSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.timeZeroSpinBox.setMaximum(300.0)
        self.timeZeroSpinBox.setProperty("value", 151.0)
        self.timeZeroSpinBox.setObjectName("timeZeroSpinBox")
        self.verticalLayout_6.addWidget(self.timeZeroSpinBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.addTimeAxisButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.addTimeAxisButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTimeAxisButton.sizePolicy().hasHeightForWidth())
        self.addTimeAxisButton.setSizePolicy(sizePolicy)
        self.addTimeAxisButton.setObjectName("addTimeAxisButton")
        self.horizontalLayout_4.addWidget(self.addTimeAxisButton)
        self.joinButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.joinButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joinButton.sizePolicy().hasHeightForWidth())
        self.joinButton.setSizePolicy(sizePolicy)
        self.joinButton.setAutoFillBackground(False)
        self.joinButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.joinButton.setObjectName("joinButton")
        self.horizontalLayout_4.addWidget(self.joinButton)
        self.calibrateButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.calibrateButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrateButton.sizePolicy().hasHeightForWidth())
        self.calibrateButton.setSizePolicy(sizePolicy)
        self.calibrateButton.setAutoFillBackground(False)
        self.calibrateButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.calibrateButton.setObjectName("calibrateButton")
        self.horizontalLayout_4.addWidget(self.calibrateButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.removeCosmicRaysButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.removeCosmicRaysButton.setEnabled(False)
        self.removeCosmicRaysButton.setObjectName("removeCosmicRaysButton")
        self.horizontalLayout_5.addWidget(self.removeCosmicRaysButton)
        self.background_end_label = QtWidgets.QLabel(self.layoutWidget1)
        self.background_end_label.setObjectName("background_end_label")
        self.horizontalLayout_5.addWidget(self.background_end_label)
        self.backgroundEndTimeSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.backgroundEndTimeSpinBox.setMinimum(-1000)
        self.backgroundEndTimeSpinBox.setMaximum(-2)
        self.backgroundEndTimeSpinBox.setProperty("value", -3)
        self.backgroundEndTimeSpinBox.setObjectName("backgroundEndTimeSpinBox")
        self.horizontalLayout_5.addWidget(self.backgroundEndTimeSpinBox)
        self.backgroundSubtractButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.backgroundSubtractButton.setEnabled(False)
        self.backgroundSubtractButton.setObjectName("backgroundSubtractButton")
        self.horizontalLayout_5.addWidget(self.backgroundSubtractButton)
        self.saveDataButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveDataButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDataButton.sizePolicy().hasHeightForWidth())
        self.saveDataButton.setSizePolicy(sizePolicy)
        self.saveDataButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.saveDataButton.setObjectName("saveDataButton")
        self.horizontalLayout_5.addWidget(self.saveDataButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16.addWidget(self.dataCorrectionGbox)
        self.kineticsGbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kineticsGbox.sizePolicy().hasHeightForWidth())
        self.kineticsGbox.setSizePolicy(sizePolicy)
        self.kineticsGbox.setObjectName("kineticsGbox")
        self.layoutWidget2 = QtWidgets.QWidget(self.kineticsGbox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 521, 331))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.kineticCentreWlSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.kineticCentreWlSpinBox.setEnabled(False)
        self.kineticCentreWlSpinBox.setMaximum(2000.0)
        self.kineticCentreWlSpinBox.setProperty("value", 500.0)
        self.kineticCentreWlSpinBox.setObjectName("kineticCentreWlSpinBox")
        self.horizontalLayout.addWidget(self.kineticCentreWlSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.kineticAveragingSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.kineticAveragingSpinBox.setEnabled(False)
        self.kineticAveragingSpinBox.setMinimum(1.0)
        self.kineticAveragingSpinBox.setMaximum(500.0)
        self.kineticAveragingSpinBox.setProperty("value", 25.0)
        self.kineticAveragingSpinBox.setObjectName("kineticAveragingSpinBox")
        self.horizontalLayout_2.addWidget(self.kineticAveragingSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kineticLogYCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.kineticLogYCheckBox.setEnabled(False)
        self.kineticLogYCheckBox.setChecked(True)
        self.kineticLogYCheckBox.setObjectName("kineticLogYCheckBox")
        self.verticalLayout.addWidget(self.kineticLogYCheckBox)
        self.kineticLogTCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.kineticLogTCheckBox.setEnabled(False)
        self.kineticLogTCheckBox.setChecked(True)
        self.kineticLogTCheckBox.setObjectName("kineticLogTCheckBox")
        self.verticalLayout.addWidget(self.kineticLogTCheckBox)
        self.kineticNormalisedCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.kineticNormalisedCheckBox.setEnabled(False)
        self.kineticNormalisedCheckBox.setChecked(True)
        self.kineticNormalisedCheckBox.setObjectName("kineticNormalisedCheckBox")
        self.verticalLayout.addWidget(self.kineticNormalisedCheckBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.saveKineticButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.saveKineticButton.setEnabled(False)
        self.saveKineticButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.saveKineticButton.setObjectName("saveKineticButton")
        self.verticalLayout_2.addWidget(self.saveKineticButton)
        self.resetButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.resetButton.setEnabled(True)
        self.resetButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_2.addWidget(self.resetButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.kineticDisplay = MplWidget(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kineticDisplay.sizePolicy().hasHeightForWidth())
        self.kineticDisplay.setSizePolicy(sizePolicy)
        self.kineticDisplay.setObjectName("kineticDisplay")
        self.verticalLayout_4.addWidget(self.kineticDisplay)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_16.addWidget(self.kineticsGbox)
        self.verticalLayout_16.setStretch(0, 2)
        self.verticalLayout_16.setStretch(1, 7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.verticalLayout_17.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iCCD Kinetics"))
        self.calibrationFileLineEdit.setText(_translate("MainWindow", "choose calibration file..."))
        self.calibrationFileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.label_12.setText(_translate("MainWindow", "File"))
        self.firstKineticBrowseButton.setText(_translate("MainWindow", "browse"))
        self.label_9.setText(_translate("MainWindow", "Start Time (ns)"))
        self.label_11.setText(_translate("MainWindow", "Gate Step (ns)"))
        self.label_13.setText(_translate("MainWindow", "Background File"))
        self.firstBackgroundLineEdit.setText(_translate("MainWindow", "         will use the period before the pulse arrives to calculate the background"))
        self.kineticFilesBrowseButton.setText(_translate("MainWindow", "browse"))
        self.moveUpButton.setText(_translate("MainWindow", "move up"))
        self.moveDownButton.setText(_translate("MainWindow", "move down"))
        self.deleteButton.setText(_translate("MainWindow", "delete"))
        self.timeSlicesGbox.setTitle(_translate("MainWindow", "Time Slices"))
        self.label_8.setText(_translate("MainWindow", "Wavelength from:"))
        self.label_10.setText(_translate("MainWindow", "to"))
        self.autoscaleCheckBox.setText(_translate("MainWindow", "Autoscale"))
        self.scaleButton.setText(_translate("MainWindow", "Scale"))
        self.dataCorrectionGbox.setTitle(_translate("MainWindow", "Data Correction"))
        self.label_7.setText(_translate("MainWindow", "Delimiter"))
        self.loadButton.setText(_translate("MainWindow", "LOAD"))
        self.label_15.setText(_translate("MainWindow", "Time Zero (ns)"))
        self.addTimeAxisButton.setText(_translate("MainWindow", "Add Time Axes"))
        self.joinButton.setText(_translate("MainWindow", "JOIN"))
        self.calibrateButton.setText(_translate("MainWindow", "CALIBRATE"))
        self.removeCosmicRaysButton.setText(_translate("MainWindow", "Remove Cosmic Rays"))
        self.background_end_label.setText(_translate("MainWindow", "Background data up to time:"))
        self.backgroundSubtractButton.setText(_translate("MainWindow", "Subtract Backgrounds"))
        self.saveDataButton.setText(_translate("MainWindow", "SAVE DATA"))
        self.kineticsGbox.setTitle(_translate("MainWindow", "Kinetics"))
        self.label.setText(_translate("MainWindow", "Wavelength"))
        self.label_2.setText(_translate("MainWindow", "Average +/-"))
        self.kineticLogYCheckBox.setText(_translate("MainWindow", "Log y-axis"))
        self.kineticLogTCheckBox.setText(_translate("MainWindow", "Log t-axis"))
        self.kineticNormalisedCheckBox.setText(_translate("MainWindow", "Normalised"))
        self.saveKineticButton.setText(_translate("MainWindow", "SAVE KINETIC"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))

from mplwidget import MplWidget
