# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputFileGbox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputFileGbox.setGeometry(QtCore.QRect(10, 10, 1171, 241))
        self.inputFileGbox.setObjectName("inputFileGbox")
        self.calibrationFileLineEdit = QtWidgets.QLineEdit(self.inputFileGbox)
        self.calibrationFileLineEdit.setEnabled(False)
        self.calibrationFileLineEdit.setGeometry(QtCore.QRect(10, 20, 1071, 20))
        self.calibrationFileLineEdit.setObjectName("calibrationFileLineEdit")
        self.calibrationFileBrowseButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.calibrationFileBrowseButton.setEnabled(False)
        self.calibrationFileBrowseButton.setGeometry(QtCore.QRect(1090, 20, 75, 23))
        self.calibrationFileBrowseButton.setObjectName("calibrationFileBrowseButton")
        self.kineticsFilesListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.kineticsFilesListWidget.setGeometry(QtCore.QRect(10, 110, 401, 121))
        self.kineticsFilesListWidget.setAcceptDrops(True)
        self.kineticsFilesListWidget.setDragEnabled(True)
        self.kineticsFilesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.kineticsFilesListWidget.setMovement(QtWidgets.QListView.Snap)
        self.kineticsFilesListWidget.setObjectName("kineticsFilesListWidget")
        self.moveUpButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.moveUpButton.setGeometry(QtCore.QRect(420, 150, 75, 21))
        self.moveUpButton.setObjectName("moveUpButton")
        self.moveDownButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.moveDownButton.setGeometry(QtCore.QRect(420, 180, 75, 21))
        self.moveDownButton.setObjectName("moveDownButton")
        self.deleteButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.deleteButton.setGeometry(QtCore.QRect(420, 210, 75, 21))
        self.deleteButton.setObjectName("deleteButton")
        self.label_9 = QtWidgets.QLabel(self.inputFileGbox)
        self.label_9.setGeometry(QtCore.QRect(500, 50, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.inputFileGbox)
        self.label_11.setGeometry(QtCore.QRect(630, 50, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.inputFileGbox)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_12.setObjectName("label_12")
        self.backgroundFilesListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.backgroundFilesListWidget.setGeometry(QtCore.QRect(760, 110, 401, 121))
        self.backgroundFilesListWidget.setAcceptDrops(True)
        self.backgroundFilesListWidget.setDragEnabled(True)
        self.backgroundFilesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.backgroundFilesListWidget.setMovement(QtWidgets.QListView.Snap)
        self.backgroundFilesListWidget.setObjectName("backgroundFilesListWidget")
        self.label_13 = QtWidgets.QLabel(self.inputFileGbox)
        self.label_13.setGeometry(QtCore.QRect(760, 50, 81, 16))
        self.label_13.setObjectName("label_13")
        self.firstKineticBrowseButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.firstKineticBrowseButton.setGeometry(QtCore.QRect(420, 80, 75, 21))
        self.firstKineticBrowseButton.setObjectName("firstKineticBrowseButton")
        self.startTimesListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.startTimesListWidget.setGeometry(QtCore.QRect(500, 110, 121, 121))
        self.startTimesListWidget.setObjectName("startTimesListWidget")
        self.gateStepListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.gateStepListWidget.setGeometry(QtCore.QRect(630, 110, 121, 121))
        self.gateStepListWidget.setObjectName("gateStepListWidget")
        self.kineticFilesBrowseButton = QtWidgets.QPushButton(self.inputFileGbox)
        self.kineticFilesBrowseButton.setGeometry(QtCore.QRect(420, 110, 75, 31))
        self.kineticFilesBrowseButton.setObjectName("kineticFilesBrowseButton")
        self.firstBackgroundLineEdit = QtWidgets.QLineEdit(self.inputFileGbox)
        self.firstBackgroundLineEdit.setEnabled(False)
        self.firstBackgroundLineEdit.setGeometry(QtCore.QRect(760, 80, 401, 20))
        self.firstBackgroundLineEdit.setObjectName("firstBackgroundLineEdit")
        self.firstKineticFileListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.firstKineticFileListWidget.setGeometry(QtCore.QRect(10, 80, 401, 21))
        self.firstKineticFileListWidget.setObjectName("firstKineticFileListWidget")
        self.firstKineticStartTimeListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.firstKineticStartTimeListWidget.setGeometry(QtCore.QRect(500, 80, 121, 21))
        self.firstKineticStartTimeListWidget.setObjectName("firstKineticStartTimeListWidget")
        self.firstKineticGateStepListWidget = QtWidgets.QListWidget(self.inputFileGbox)
        self.firstKineticGateStepListWidget.setGeometry(QtCore.QRect(630, 80, 121, 21))
        self.firstKineticGateStepListWidget.setObjectName("firstKineticGateStepListWidget")
        self.dataCorrectionGbox = QtWidgets.QGroupBox(self.centralwidget)
        self.dataCorrectionGbox.setGeometry(QtCore.QRect(640, 260, 541, 111))
        self.dataCorrectionGbox.setObjectName("dataCorrectionGbox")
        self.saveDataButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.saveDataButton.setEnabled(False)
        self.saveDataButton.setGeometry(QtCore.QRect(450, 80, 81, 23))
        self.saveDataButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.saveDataButton.setObjectName("saveDataButton")
        self.backgroundSubtractButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.backgroundSubtractButton.setEnabled(False)
        self.backgroundSubtractButton.setGeometry(QtCore.QRect(320, 80, 121, 23))
        self.backgroundSubtractButton.setObjectName("backgroundSubtractButton")
        self.loadButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.loadButton.setGeometry(QtCore.QRect(100, 20, 75, 41))
        self.loadButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.loadButton.setObjectName("loadButton")
        self.label_15 = QtWidgets.QLabel(self.dataCorrectionGbox)
        self.label_15.setGeometry(QtCore.QRect(190, 20, 81, 16))
        self.label_15.setObjectName("label_15")
        self.addTimeAxisButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.addTimeAxisButton.setEnabled(False)
        self.addTimeAxisButton.setGeometry(QtCore.QRect(280, 20, 101, 41))
        self.addTimeAxisButton.setObjectName("addTimeAxisButton")
        self.background_end_label = QtWidgets.QLabel(self.dataCorrectionGbox)
        self.background_end_label.setGeometry(QtCore.QRect(130, 80, 141, 20))
        self.background_end_label.setObjectName("background_end_label")
        self.joinButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.joinButton.setEnabled(False)
        self.joinButton.setGeometry(QtCore.QRect(450, 20, 81, 41))
        self.joinButton.setAutoFillBackground(False)
        self.joinButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.joinButton.setObjectName("joinButton")
        self.timeZeroSpinBox = QtWidgets.QDoubleSpinBox(self.dataCorrectionGbox)
        self.timeZeroSpinBox.setGeometry(QtCore.QRect(190, 40, 81, 22))
        self.timeZeroSpinBox.setMaximum(300.0)
        self.timeZeroSpinBox.setProperty("value", 151.0)
        self.timeZeroSpinBox.setObjectName("timeZeroSpinBox")
        self.backgroundEndTimeSpinBox = QtWidgets.QSpinBox(self.dataCorrectionGbox)
        self.backgroundEndTimeSpinBox.setGeometry(QtCore.QRect(270, 80, 41, 22))
        self.backgroundEndTimeSpinBox.setMinimum(-1000)
        self.backgroundEndTimeSpinBox.setMaximum(-2)
        self.backgroundEndTimeSpinBox.setProperty("value", -3)
        self.backgroundEndTimeSpinBox.setObjectName("backgroundEndTimeSpinBox")
        self.delimiterComboBox = QtWidgets.QComboBox(self.dataCorrectionGbox)
        self.delimiterComboBox.setGeometry(QtCore.QRect(8, 40, 81, 22))
        self.delimiterComboBox.setObjectName("delimiterComboBox")
        self.label_7 = QtWidgets.QLabel(self.dataCorrectionGbox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_7.setObjectName("label_7")
        self.removeCosmicRaysButton = QtWidgets.QPushButton(self.dataCorrectionGbox)
        self.removeCosmicRaysButton.setEnabled(False)
        self.removeCosmicRaysButton.setGeometry(QtCore.QRect(10, 80, 111, 23))
        self.removeCosmicRaysButton.setObjectName("removeCosmicRaysButton")
        self.timeSlicesGbox = QtWidgets.QGroupBox(self.centralwidget)
        self.timeSlicesGbox.setGeometry(QtCore.QRect(10, 260, 621, 551))
        self.timeSlicesGbox.setObjectName("timeSlicesGbox")
        self.timeSliceDisplay = MplWidget(self.timeSlicesGbox)
        self.timeSliceDisplay.setGeometry(QtCore.QRect(10, 20, 601, 431))
        self.timeSliceDisplay.setObjectName("timeSliceDisplay")
        self.autoscaleCheckBox = QtWidgets.QCheckBox(self.timeSlicesGbox)
        self.autoscaleCheckBox.setEnabled(False)
        self.autoscaleCheckBox.setGeometry(QtCore.QRect(540, 490, 70, 17))
        self.autoscaleCheckBox.setChecked(True)
        self.autoscaleCheckBox.setObjectName("autoscaleCheckBox")
        self.scaleButton = QtWidgets.QPushButton(self.timeSlicesGbox)
        self.scaleButton.setEnabled(False)
        self.scaleButton.setGeometry(QtCore.QRect(540, 520, 75, 23))
        self.scaleButton.setObjectName("scaleButton")
        self.label_8 = QtWidgets.QLabel(self.timeSlicesGbox)
        self.label_8.setGeometry(QtCore.QRect(10, 460, 87, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.timeSlicesGbox)
        self.label_10.setGeometry(QtCore.QRect(200, 460, 16, 16))
        self.label_10.setObjectName("label_10")
        self.timeSliceWlMinSpinBox = QtWidgets.QDoubleSpinBox(self.timeSlicesGbox)
        self.timeSliceWlMinSpinBox.setEnabled(False)
        self.timeSliceWlMinSpinBox.setGeometry(QtCore.QRect(110, 460, 81, 22))
        self.timeSliceWlMinSpinBox.setMaximum(2000.0)
        self.timeSliceWlMinSpinBox.setObjectName("timeSliceWlMinSpinBox")
        self.timeSliceWlMaxSpinBox = QtWidgets.QDoubleSpinBox(self.timeSlicesGbox)
        self.timeSliceWlMaxSpinBox.setEnabled(False)
        self.timeSliceWlMaxSpinBox.setGeometry(QtCore.QRect(220, 460, 81, 22))
        self.timeSliceWlMaxSpinBox.setMaximum(2000.0)
        self.timeSliceWlMaxSpinBox.setProperty("value", 2000.0)
        self.timeSliceWlMaxSpinBox.setObjectName("timeSliceWlMaxSpinBox")
        self.timeSlider = QtWidgets.QScrollBar(self.timeSlicesGbox)
        self.timeSlider.setGeometry(QtCore.QRect(10, 510, 511, 16))
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.kineticsGbox = QtWidgets.QGroupBox(self.centralwidget)
        self.kineticsGbox.setGeometry(QtCore.QRect(640, 380, 541, 431))
        self.kineticsGbox.setObjectName("kineticsGbox")
        self.label = QtWidgets.QLabel(self.kineticsGbox)
        self.label.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.kineticsGbox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.kineticAveragingSpinBox = QtWidgets.QDoubleSpinBox(self.kineticsGbox)
        self.kineticAveragingSpinBox.setEnabled(False)
        self.kineticAveragingSpinBox.setGeometry(QtCore.QRect(80, 60, 71, 22))
        self.kineticAveragingSpinBox.setMinimum(1.0)
        self.kineticAveragingSpinBox.setMaximum(500.0)
        self.kineticAveragingSpinBox.setProperty("value", 25.0)
        self.kineticAveragingSpinBox.setObjectName("kineticAveragingSpinBox")
        self.kineticDisplay = MplWidget(self.kineticsGbox)
        self.kineticDisplay.setGeometry(QtCore.QRect(10, 100, 521, 321))
        self.kineticDisplay.setObjectName("kineticDisplay")
        self.kineticLogTCheckBox = QtWidgets.QCheckBox(self.kineticsGbox)
        self.kineticLogTCheckBox.setEnabled(False)
        self.kineticLogTCheckBox.setGeometry(QtCore.QRect(200, 50, 75, 17))
        self.kineticLogTCheckBox.setChecked(True)
        self.kineticLogTCheckBox.setObjectName("kineticLogTCheckBox")
        self.kineticLogYCheckBox = QtWidgets.QCheckBox(self.kineticsGbox)
        self.kineticLogYCheckBox.setEnabled(False)
        self.kineticLogYCheckBox.setGeometry(QtCore.QRect(200, 30, 75, 17))
        self.kineticLogYCheckBox.setChecked(True)
        self.kineticLogYCheckBox.setObjectName("kineticLogYCheckBox")
        self.kineticNormalisedCheckBox = QtWidgets.QCheckBox(self.kineticsGbox)
        self.kineticNormalisedCheckBox.setEnabled(False)
        self.kineticNormalisedCheckBox.setGeometry(QtCore.QRect(200, 70, 75, 17))
        self.kineticNormalisedCheckBox.setChecked(True)
        self.kineticNormalisedCheckBox.setObjectName("kineticNormalisedCheckBox")
        self.saveKineticButton = QtWidgets.QPushButton(self.kineticsGbox)
        self.saveKineticButton.setEnabled(False)
        self.saveKineticButton.setGeometry(QtCore.QRect(450, 20, 81, 23))
        self.saveKineticButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.saveKineticButton.setObjectName("saveKineticButton")
        self.kineticCentreWlSpinBox = QtWidgets.QDoubleSpinBox(self.kineticsGbox)
        self.kineticCentreWlSpinBox.setEnabled(False)
        self.kineticCentreWlSpinBox.setGeometry(QtCore.QRect(80, 30, 71, 22))
        self.kineticCentreWlSpinBox.setMaximum(2000.0)
        self.kineticCentreWlSpinBox.setProperty("value", 500.0)
        self.kineticCentreWlSpinBox.setObjectName("kineticCentreWlSpinBox")
        self.resetButton = QtWidgets.QPushButton(self.kineticsGbox)
        self.resetButton.setEnabled(True)
        self.resetButton.setGeometry(QtCore.QRect(450, 60, 81, 23))
        self.resetButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iCCD Kinetics"))
        self.inputFileGbox.setTitle(_translate("MainWindow", "Input Files"))
        self.calibrationFileLineEdit.setText(_translate("MainWindow", "<calibration file>"))
        self.calibrationFileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.moveUpButton.setText(_translate("MainWindow", "move up"))
        self.moveDownButton.setText(_translate("MainWindow", "move down"))
        self.deleteButton.setText(_translate("MainWindow", "delete"))
        self.label_9.setText(_translate("MainWindow", "Start Time (ns)"))
        self.label_11.setText(_translate("MainWindow", "Gate Step (ns)"))
        self.label_12.setText(_translate("MainWindow", "File"))
        self.label_13.setText(_translate("MainWindow", "Background File"))
        self.firstKineticBrowseButton.setText(_translate("MainWindow", "browse"))
        self.kineticFilesBrowseButton.setText(_translate("MainWindow", "browse"))
        self.firstBackgroundLineEdit.setText(_translate("MainWindow", "         will use the period before the pulse arrives to calculate the background"))
        self.dataCorrectionGbox.setTitle(_translate("MainWindow", "Data Correction"))
        self.saveDataButton.setText(_translate("MainWindow", "SAVE DATA"))
        self.backgroundSubtractButton.setText(_translate("MainWindow", "Subtract Backgrounds"))
        self.loadButton.setText(_translate("MainWindow", "LOAD"))
        self.label_15.setText(_translate("MainWindow", "Time Zero (ns)"))
        self.addTimeAxisButton.setText(_translate("MainWindow", "Add Time Axes"))
        self.background_end_label.setText(_translate("MainWindow", "Background data up to time:"))
        self.joinButton.setText(_translate("MainWindow", "JOIN"))
        self.label_7.setText(_translate("MainWindow", "Delimiter"))
        self.removeCosmicRaysButton.setText(_translate("MainWindow", "Remove Cosmic Rays"))
        self.timeSlicesGbox.setTitle(_translate("MainWindow", "Time Slices"))
        self.autoscaleCheckBox.setText(_translate("MainWindow", "Autoscale"))
        self.scaleButton.setText(_translate("MainWindow", "Scale"))
        self.label_8.setText(_translate("MainWindow", "Wavelength from:"))
        self.label_10.setText(_translate("MainWindow", "to"))
        self.kineticsGbox.setTitle(_translate("MainWindow", "Kinetics"))
        self.label.setText(_translate("MainWindow", "Wavelength"))
        self.label_2.setText(_translate("MainWindow", "Average +/-"))
        self.kineticLogTCheckBox.setText(_translate("MainWindow", "Log t-axis"))
        self.kineticLogYCheckBox.setText(_translate("MainWindow", "Log y-axis"))
        self.kineticNormalisedCheckBox.setText(_translate("MainWindow", "Normalised"))
        self.saveKineticButton.setText(_translate("MainWindow", "SAVE KINETIC"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))

from mplwidget import MplWidget
